server:
  port: 8080

mqtt:
  hostUrl: tcp://mqtt.zhouhong.icu:1883
  username: admin
  password: public
  ## 服务端 clientId (发送端自己定义)
  clientId: service_client_id
  cleanSession: true
  reconnect: true
  timeout: 100
  keepAlive: 100
  defaultTopic: topic111
  qos: 0
